### ISSUE TITLE
Collation of club specific results.

### ISSUE THREAD

**Issue by dpawson** [parkrun/parkrunAPI#11]
About to screen scrape from 'latest' page, I found the objection.
My use case is to collate results, filter by our club then isolate PB figures
for runners at our weekly meets.
It seems I can't do this without access to the XML (preferred) or json source.

Is this planned please? We can't be the only ones to manually scrape
results?

**Comment by rleyton** [comment]
Hi there. Sorry for delay in responding. Issues here really intended to be regarding the API client libraries, rather than general API queries. These best sent via parkrun support (get in touch via https://support.parkrun.com). You can also review and accept the terms and conditions at https://www.parkrun.com/profile/developer/
